CREATE VIEW s_grnplm_vd_hr_edp_srv_wf.vw_swf AS
 WITH vw_swf_wf AS (
         SELECT (COALESCE((a.wf_end)::timestamp with time zone, now()) >= now()) AS active,
            ((a.wf_last >= (COALESCE((a.wf_next)::timestamp with time zone, now()) - a.wf_interval)) AND (COALESCE((a.wf_next)::timestamp with time zone, now()) >= now())) AS done,
            a.wf_next,
            a.reselt,
            a.wf_last_end,
            a.wf_id,
            a.wf_order,
            a.wf_name,
            a.wf_exec,
            a.wf_beg,
            a.wf_interval,
            a.wf_end,
            a.wf_relations,
            a.wf_waits,
            a.wf_last,
            a.wf_duration,
            a.wf_swf,
            a.wf_reselt,
            a.wf_expire,
            a.ctl_wf_id
           FROM ( SELECT s_grnplm_vd_hr_edp_srv_wf.pr_swf_get_next(a_1.wf_beg, a_1.wf_interval, (a_1.wf_last + a_1.wf_duration), a_1.wf_end) AS wf_next,
                    (COALESCE((a_1.wf_reselt ->> 'reselt'::text), (a_1.wf_reselt ->> 'res'::text), (a_1.wf_reselt ->> 'result'::text)))::integer AS reselt,
                    (a_1.wf_last + a_1.wf_duration) AS wf_last_end,
                    a_1.wf_id,
                    a_1.wf_order,
                    a_1.wf_name,
                    a_1.wf_exec,
                    a_1.wf_beg,
                    a_1.wf_interval,
                    a_1.wf_end,
                    a_1.wf_relations,
                    a_1.wf_waits,
                    a_1.wf_last,
                    a_1.wf_duration,
                    a_1.wf_swf,
                    a_1.wf_reselt,
                    a_1.wf_expire,
                    a_1.ctl_wf_id
                   FROM s_grnplm_vd_hr_edp_srv_wf.tb_swf a_1) a
        )
 SELECT row_number() OVER (PARTITION BY b.todo ORDER BY b.rn) AS rn_td,
    (COALESCE((b.wf_end)::timestamp with time zone, now()) >= now()) AS active,
    b.rn,
    b.todo,
    b.done,
    b.ready,
    b.wf_next,
    b.wf_expire,
    b.wf_id,
    b.wf_order,
    b.wf_name,
    b.wf_exec,
    b.wf_beg,
    b.wf_interval,
    b.wf_end,
    b.wf_relations,
    b.wf_waits,
    b.wf_last,
    b.wf_duration,
    b.wf_last_end,
    b.wf_swf,
    b.wf_reselt,
    b.rel_done,
    b.rel_ok,
    b.rel_min,
    b.rel_cnt,
    b.rel_done_cnt,
    b.rel_note,
    b.wait_done,
    b.wait_ok,
    b.wait_min,
    b.wait_cnt,
    b.wait_done_cnt,
    b.wait_note,
    b.not_ok_note,
    b.ctl_wf_id
   FROM ( SELECT row_number() OVER (ORDER BY GREATEST(a.wf_last_end, a.rel_last, a.wait_last, a.wf_next), a.wf_order, a.wf_id) AS rn,
            ((((a.wf_next < now()) AND (a.wait_done IS TRUE)) AND (a.rel_done IS TRUE)) AND (a.active IS TRUE)) AS todo,
            a.done,
            GREATEST(a.wf_last_end, a.rel_last, a.wait_last, a.wf_next) AS ready,
            a.wf_next,
            a.wf_expire,
            a.wf_id,
            a.wf_order,
            a.wf_name,
            a.wf_exec,
            a.wf_beg,
            a.wf_interval,
            a.wf_end,
            a.wf_relations,
            a.wf_waits,
            a.wf_last,
            a.wf_duration,
            a.wf_last_end,
            a.wf_swf,
            a.wf_reselt,
            a.rel_done,
            a.rel_ok,
            a.rel_min,
            a.rel_cnt,
            a.rel_done_cnt,
            a.rel_note,
            a.wait_done,
            a.wait_ok,
            a.wait_min,
            a.wait_cnt,
            a.wait_done_cnt,
            a.wait_note,
            a.not_ok_note,
            a.ctl_wf_id
           FROM ( SELECT a_1.active,
                    a_1.done,
                    a_1.wf_next,
                    a_1.reselt,
                    a_1.wf_last_end,
                    a_1.wf_id,
                    a_1.wf_order,
                    a_1.wf_name,
                    a_1.wf_exec,
                    a_1.wf_beg,
                    a_1.wf_interval,
                    a_1.wf_end,
                    a_1.wf_relations,
                    a_1.wf_waits,
                    a_1.wf_last,
                    a_1.wf_duration,
                    a_1.wf_swf,
                    a_1.wf_reselt,
                    a_1.wf_expire,
                    a_1.ctl_wf_id,
                    COALESCE(b_1.rel_done, true) AS rel_done,
                    COALESCE(b_1.rel_ok, true) AS rel_ok,
                    b_1.rel_min,
                    b_1.rel_last,
                    b_1.rel_cnt,
                    b_1.rel_done_cnt,
                    b_1.rel_note,
                    b_1.not_ok_note,
                    COALESCE(c.wait_done, true) AS wait_done,
                    COALESCE(c.wait_ok, true) AS wait_ok,
                    c.wait_min,
                    c.wait_last,
                    c.wait_cnt,
                    c.wait_done_cnt,
                    c.wait_note
                   FROM ((vw_swf_wf a_1
                     LEFT JOIN ( SELECT a_2.wf_name AS rel_id,
                            (COALESCE(min((b_2.done)::integer), 0))::boolean AS rel_done,
                            (COALESCE(min(((b_2.reselt >= 1))::integer), 0))::boolean AS rel_ok,
                            min(b_2.reselt) AS rel_min,
                            max(b_2.wf_last_end) AS rel_last,
                            COALESCE(count(1), (0)::bigint) AS rel_cnt,
                            COALESCE(sum((b_2.done)::integer), (0)::bigint) AS rel_done_cnt,
                            string_agg(
                                CASE
                                    WHEN (NOT b_2.done) THEN b_2.wf_name
                                    ELSE NULL::text
                                END, ', '::text) AS rel_note,
                            string_agg(
                                CASE
                                    WHEN (NOT (b_2.reselt >= 1)) THEN b_2.wf_name
                                    ELSE NULL::text
                                END, ', '::text) AS not_ok_note
                           FROM (( SELECT tb_swf.wf_name,
                                    unnest(tb_swf.wf_relations) AS wf_relation
                                   FROM s_grnplm_vd_hr_edp_srv_wf.tb_swf) a_2
                             LEFT JOIN ( SELECT a_3.wf_id,
                                    a_3.wf_name,
                                    a_3.done,
                                    a_3.reselt,
                                    a_3.wf_interval,
                                    a_3.wf_last,
                                    a_3.wf_last_end
                                   FROM vw_swf_wf a_3) b_2 ON ((a_2.wf_relation = b_2.wf_name)))
                          GROUP BY a_2.wf_name) b_1 ON ((a_1.wf_name = b_1.rel_id)))
                     LEFT JOIN ( SELECT a_2.wf_name AS wait_id,
                            (COALESCE(min((b_2.done)::integer), 0))::boolean AS wait_done,
                            (COALESCE(min(((b_2.reselt >= 1))::integer), 0))::boolean AS wait_ok,
                            min(b_2.reselt) AS wait_min,
                            max(b_2.wf_last_end) AS wait_last,
                            COALESCE(count(1), (0)::bigint) AS wait_cnt,
                            COALESCE(sum((b_2.done)::integer), (0)::bigint) AS wait_done_cnt,
                            string_agg(
                                CASE
                                    WHEN (NOT b_2.done) THEN b_2.wf_name
                                    ELSE NULL::text
                                END, ', '::text) AS wait_note
                           FROM (( SELECT tb_swf.wf_name,
                                    unnest(tb_swf.wf_waits) AS wf_wait
                                   FROM s_grnplm_vd_hr_edp_srv_wf.tb_swf) a_2
                             LEFT JOIN ( SELECT a_3.wf_id,
                                    a_3.wf_name,
                                    a_3.done,
                                    a_3.reselt,
                                    a_3.wf_interval,
                                    a_3.wf_last,
                                    a_3.wf_last_end
                                   FROM vw_swf_wf a_3) b_2 ON ((a_2.wf_wait = b_2.wf_name)))
                          GROUP BY a_2.wf_name) c ON ((a_1.wf_name = c.wait_id)))) a) b
  ORDER BY (COALESCE((b.wf_end)::timestamp with time zone, now()) >= now()), b.todo DESC, b.rn;


COMMENT ON VIEW s_grnplm_vd_hr_edp_srv_wf.vw_swf IS 'Текущее состояние всех super-workflow с расписанием, прогрессом и статусом активности';
