CREATE TABLE s_grnplm_vd_hr_edp_srv_wf.tb_log_fld_stat_tmp (
	ts timestamp with time zone null,
	tbl_name text null,
	fld_name text null,
	fld_num integer null,
	fld_type text null,
	is_not_null boolean null,
	is_uniq boolean null,
	min text null,
	max text null,
	dist_cnt bigint null,
	null_cnt bigint null,
	cnt bigint null,
	min_cnt bigint null,
	max_cnt bigint null,
	avg_cnt bigint null,
	min_size integer null,
	avg_size integer null,
	max_size integer null,
	min_len integer null,
	avg_len integer null,
	max_len integer null,
	cnt_bool bigint null,
	cnt_dt bigint null,
	cnt_regclass bigint null,
	cnt_int bigint null,
	cnt_float bigint null,
	cnt_uuid bigint null,
	cnt_array bigint null,
	cnt_json bigint null
)
DISTRIBUTED RANDOMLY;