CREATE TABLE s_grnplm_vd_hr_edp_srv_wf.tb_swf_log_wf (
	now timestamp with time zone null,
	rn_td bigint null,
	active boolean null,
	rn bigint null,
	todo boolean null,
	done boolean null,
	ready timestamp without time zone null,
	wf_next timestamp without time zone null,
	wf_id integer null,
	wf_order integer null,
	wf_name text null,
	wf_exec text null,
	wf_beg timestamp without time zone null,
	wf_interval interval null,
	wf_end timestamp without time zone null,
	wf_relations text[] null,
	wf_waits text[] null,
	wf_last timestamp without time zone null,
	wf_duration interval null,
	wf_last_end timestamp without time zone null,
	wf_swf text null,
	wf_reselt json null,
	rel_done boolean null,
	rel_ok boolean null,
	rel_min integer null,
	rel_note json null,
	wait_done boolean null,
	wait_ok boolean null,
	wait_min integer null,
	wait_note json null
)
DISTRIBUTED BY (now);