CREATE TABLE s_grnplm_vd_hr_edp_srv_wf.tmp_tb_sberindex_df_city (
	kpi_id integer null,
	report_dt date null,
	dynamictype integer null,
	axis_1 integer null,
	axis_2 text null,
	axis_3 text null,
	axis_4 text null,
	nversionid integer null,
	decile_1 numeric null,
	decile_2 numeric null,
	decile_3 numeric null,
	decile_4 numeric null,
	median numeric null,
	decile_6 numeric null,
	decile_7 numeric null,
	decile_8 numeric null,
	decile_9 numeric null,
	mean numeric null,
	scomment text null,
	ntotaltype integer null,
	distinct_inn integer null,
	distinct_epk_id integer null,
	fot_top1_rate numeric null,
	fot_top3_rate numeric null,
	fot_top5_rate numeric null,
	client_cnt_top1_rate numeric null,
	client_cnt_top3_rate numeric null,
	client_cnt_top5_rate numeric null,
	top1_same1 integer null,
	top3_same2 integer null,
	top5_same3 integer null
)
WITH (appendonly=true, orientation=column, compresstype=zstd, compresslevel=3)
DISTRIBUTED BY (axis_1);